/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppAccordion: (typeof import('./src/components/partials/AppAccordion.vue'))['default']
    AppAvatar: (typeof import('./src/components/ui/AppAvatar.vue'))['default']
    AppBarChart: (typeof import('./src/components/partials/AppBarChart.vue'))['default']
    AppBox: (typeof import('./src/components/ui/AppBox.vue'))['default']
    AppButton: (typeof import('./src/components/ui/AppButton.vue'))['default']
    AppCalendar: (typeof import('./src/components/partials/AppCalendar.vue'))['default']
    AppCard: (typeof import('./src/components/ui/AppCard.vue'))['default']
    AppCarousel: (typeof import('./src/components/partials/AppCarousel.vue'))['default']
    AppCheckbox: (typeof import('./src/components/ui/AppCheckbox.vue'))['default']
    AppCodeInput: (typeof import('./src/components/ui/AppCodeInput.vue'))['default']
    AppComment: (typeof import('./src/components/partials/AppComment.vue'))['default']
    AppDragFile: (typeof import('./src/components/partials/AppDragFile.vue'))['default']
    AppEssayCompetences: (typeof import('./components/partials/AppEssayCompetences.vue'))['default']
    AppEssayCompetencesProgress: (typeof import('./components/partials/AppEssayCompetencesProgress.vue'))['default']
    AppEssayInstructions: (typeof import('./components/partials/AppEssayInstructions.vue'))['default']
    AppLineChart: (typeof import('./src/components/partials/AppLineChart.vue'))['default']
    AppLoading: (typeof import('./src/components/ui/AppLoading.vue'))['default']
    AppModal: (typeof import('./src/components/partials/AppModal.vue'))['default']
    AppPagination: (typeof import('./src/components/partials/AppPagination.vue'))['default']
    AppPost: (typeof import('./src/components/partials/AppPost.vue'))['default']
    AppQuestionAlternatives: (typeof import('./components/partials/AppQuestionAlternatives.vue'))['default']
    AppStep: (typeof import('./src/components/partials/AppStep.vue'))['default']
    AppTable: (typeof import('./src/components/partials/AppTable.vue'))['default']
    AppText: (typeof import('./src/components/ui/AppText.vue'))['default']
    AppTimer: (typeof import('./src/components/ui/AppTimer.vue'))['default']
    Container: (typeof import('./src/components/layout/default/Container.vue'))['default']
    English: (typeof import('./components/icons/English.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    Spanish: (typeof import('./components/icons/Spanish.vue'))['default']
    StudentContainer: (typeof import('./components/layout/student/StudentContainer.vue'))['default']
    StudentHeader: (typeof import('./components/layout/student/StudentHeader.vue'))['default']
    StudentSidebar: (typeof import('./components/layout/student/StudentSidebar.vue'))['default']
  }
}
